### ISSUE TITLE
bsoup error

### ISSUE THREAD

**Issue by nichsedge** [arifer612/exportMDL#2]
`
Successfully logged in
Traceback (most recent call last):
  File "C:\Users\mal\Documents\projects\exportMDL\exportMDL.py", line 242, in <module>
    main(sys.argv[1:])
  File "C:\Users\mal\Documents\projects\exportMDL\exportMDL.py", line 238, in main
    exportList(args.file, args.quiet, *[i for i in fields if fields[i]])
  File "C:\Users\mal\Documents\projects\exportMDL\exportMDL.py", line 164, in exportList
    myDramaList = dramaList(_login(), suppress, *args)
  File "C:\Users\mal\Documents\projects\exportMDL\exportMDL.py", line 158, in dramaList
    lists[key][showID].update(userInfo(showID))
  File "C:\Users\mal\Documents\projects\exportMDL\exportMDL.py", line 124, in userInfo
    infoSoup = soup(f"{siteRoot}/v1/users/watchaction/{ID}",
KeyError: 'data'
`

using google sheet is simpler lol:

IMPORTHTML("https://mydramalist.com/dramalist/<username>", "table", 1)

**Comment by arifer612** [comment]
Thanks for the feedback. I made this script 3 years ago for a version of MDL that is completely out-of-date, so naturally it would fail. If Google Sheets is good for you, then that's good! Feel free to use it :)

This project is very low on my list of priority so I will probably not fix this, not at least until I have enough free time.
